# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

with builtins;
with lib;

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = splitString "#" url;
      url_base = elemAt parts 0;
      url_without_query = elemAt (splitString "?" url_base) 0;
      rev_base = elemAt parts 1;
      rev = if match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = splitString "://" url;
      proto = elemAt parts 0;
      path = elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "12201903acc4c49d6f5df082412cdd5b3274e6a89b7ef64d49eb2badefceee68135a";
    path = fetchZigArtifact {
      name = "keylib";
      url = "https://github.com/r4gus/keylib/archive/refs/tags/0.5.3.tar.gz";
      hash = "sha256-ejnoz4QvBIIet6yb0NNPfoyxJ1kfwuIz+G3RD397QgQ=";
    };
  }
  {
    name = "12209a78f8c31b6d65d2249082dc824da4a191f6f7be6a1c1740fc093b765c5ebeea";
    path = fetchZigArtifact {
      name = "zbor";
      url = "https://github.com/r4gus/zbor/archive/refs/tags/0.15.0.tar.gz";
      hash = "sha256-ij/4ELA6Hp3Mo3Bupw3jNWAgTmcRnawWw7gohNo2K50=";
    };
  }
  {
    name = "1220e65a0ac25c2f68a5024986bd73a2be7ea269c9ea83d5e624df74683194a38a35";
    path = fetchZigArtifact {
      name = "hidapi";
      url = "https://github.com/r4gus/hidapi/archive/master.tar.gz";
      hash = "sha256-Nxjb7D8LdT1NwYXbpop77Y3amSASOTWgM9gsUHmAzqQ=";
    };
  }
  {
    name = "1220b4deeb4ec1ec3493ea934905356384561b725dba69d1fbf6a25cb398716dd05b";
    path = fetchZigArtifact {
      name = "uuid";
      url = "https://github.com/r4gus/uuid-zig/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-qhPeYoYs0rix8TwIygBTbKoZNgiScvCr560XYOgsqp0=";
    };
  }
  {
    name = "1220fb3f3644bef07f074357ca818990973ddc72d76b638f3a71af059571fc8716a0";
    path = fetchZigArtifact {
      name = "ccdb";
      url = "https://github.com/r4gus/ccdb/archive/refs/tags/0.2.0.tar.gz";
      hash = "sha256-QdyBd2SmA/W1H6DP1IJZaeV1ZZmN85hhJQMScgehe8Y=";
    };
  }
  {
    name = "122062d301a203d003547b414237229b09a7980095061697349f8bef41be9c30266b";
    path = fetchZigArtifact {
      name = "clap";
      url = "https://github.com/Hejsil/zig-clap/archive/refs/tags/0.9.1.tar.gz";
      hash = "sha256-7qxm/4xb+58MGG+iUzssUtR97OG2dRjAqyS0BAet4HY=";
    };
  }
]
